// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC54OdgFhaR92lcNorAN8D30bCEvH4PJWc',
    appId: '1:865688251728:web:fe5c4a463eb8f02ecc1055',
    messagingSenderId: '865688251728',
    projectId: 'mollah-and-sons',
    authDomain: 'mollah-and-sons.firebaseapp.com',
    storageBucket: 'mollah-and-sons.firebasestorage.app',
    measurementId: 'G-JRY4Q0VKV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8b65YtMsHgvxj_H-kCjuW-X9CVQVZoM',
    appId: '1:326155030285:android:348364587d0d0767f4aa44',
    messagingSenderId: '326155030285',
    projectId: 'mollah-and-sons-fertilizer',
    storageBucket: 'mollah-and-sons-fertilizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdsIDu_O5KZhKd-X-H8k6xKvUxtqDKWDY',
    appId: '1:865688251728:ios:9eb8d346f365d29ccc1055',
    messagingSenderId: '865688251728',
    projectId: 'mollah-and-sons',
    storageBucket: 'mollah-and-sons.firebasestorage.app',
    iosBundleId: 'com.example.alif.mollahAndSons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdsIDu_O5KZhKd-X-H8k6xKvUxtqDKWDY',
    appId: '1:865688251728:ios:9eb8d346f365d29ccc1055',
    messagingSenderId: '865688251728',
    projectId: 'mollah-and-sons',
    storageBucket: 'mollah-and-sons.firebasestorage.app',
    iosBundleId: 'com.example.alif.mollahAndSons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC54OdgFhaR92lcNorAN8D30bCEvH4PJWc',
    appId: '1:865688251728:web:ca1dda128cc9c5a8cc1055',
    messagingSenderId: '865688251728',
    projectId: 'mollah-and-sons',
    authDomain: 'mollah-and-sons.firebaseapp.com',
    storageBucket: 'mollah-and-sons.firebasestorage.app',
    measurementId: 'G-QS6ZJZK5GR',
  );

}